# Site
name: 'Devotions'
description: 'My quiet time and bible study notes.'
logo: ''
favicon: 'assets/images/favicon.png'

github-url: 'https://jinglescode.github.io/devotions'
baseurl: '/'

disqus: ''
email: 'jinglescode@gmail.com'
mailchimp-list: ''

include: ["_pages"]
permalink: /:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
 
# Defaults
defaults:
  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page

    scope:
      path: "/docs/*"
    values:
      sitemap: false
  
permalink: pretty
      
# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10

# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]